### ISSUE TITLE
Chams crashing

### ISSUE THREAD

**Issue by aysx** [spirthack/CSGOSimple#47]
After update when i turn on chams then it crash.

**Comment by anarh1st47** [comment]
can confirm bug exist, will debug

**Comment by anarh1st47** [comment]
fixed in https://github.com/spirthack/CSGOSimple/commit/0c4f8022c87d7ad12b8610a94dedcd5e2de89a4e

tldr:
Var destructor removed useful shit when it worked with Color class, so i decided to use smart pointers. Some smart people said about std::any and map to me but who am i to use it :trollface: (tbh idk how to use it properly, it works with pointers so strange)
